<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    public $cungPhi = [
        1924 => ['Giáp Tý', 'Kim', 'Tốn', 'Khôn'],
        1925 => ['Ất Sửu', 'Kim', 'Chấn', 'Chấn'],
        1926 => ['Bính Dần', 'Hỏa', 'Khôn', 'Tốn'],
        1927 => ['Đinh Mão', 'Hỏa', 'Khảm', 'Cấn'],
        1928 => ['Mậu Thìn', 'Mộc', 'Ly', 'Càn'],
        1929 => ['Kỷ Tỵ', 'Mộc', 'Cấn', 'Đoài'],
        1930 => ['Canh Ngọ', 'Thổ', 'Đoài', 'Cấn'],
        1931 => ['Tân Mùi', 'Thổ', 'Càn', 'Ly'],
        1932 => ['Nhâm Thân', 'Kim', 'Khôn', 'Khảm'],
        1933 => ['Quý Dậu', 'Kim', 'Tốn', 'Khôn'],
        1934 => ['Giáp Tuất', 'Hỏa', 'Chấn', 'Chấn'],
        1935 => ['Ất Hợi', 'Hỏa', 'Khôn', 'Tốn'],
        1936 => ['Bính Tý', 'Thủy', 'Khảm', 'Cấn'],
        1937 => ['Đinh Sửu', 'Thủy', 'Ly', 'Càn'],
        1938 => ['Mậu Dần', 'Thổ', 'Cấn', 'Đoài'],
        1939 => ['Kỷ Mão', 'Thổ', 'Đoài', 'Cấn'],
        1940 => ['Canh Thìn', 'Kim', 'Càn', 'Ly'],
        1941 => ['Tân Tỵ', 'Kim', 'Khôn', 'Khảm'],
        1942 => ['Nhâm Ngọ', 'Mộc', 'Tốn', 'Khôn'],
        1943 => ['Quý Mùi', 'Mộc', 'Chấn', 'Chấn'],
        1944 => ['Giáp Thân', 'Thủy', 'Khôn', 'Tốn'],
        1945 => ['Ất Dậu', 'Thủy', 'Khảm', 'Cấn'],
        1946 => ['Bính Tuất', 'Thổ', 'Ly', 'Càn'],
        1947 => ['Đinh Hợi', 'Thổ', 'Cấn', 'Đoài'],
        1948 => ['Mậu Tý', 'Hỏa', 'Đoài', 'Cấn'],
        1949 => ['Kỷ Sửu', 'Hỏa', 'Càn', 'Ly'],
        1950 => ['Canh Dần', 'Mộc', 'Khôn', 'Khảm'],
        1951 => ['Tân Mão', 'Mộc', 'Tốn', 'Khôn'],
        1952 => ['Nhâm Thìn', 'Thủy', 'Chấn', 'Chấn'],
        1953 => ['Quý Tỵ', 'Thủy', 'Khôn', 'Tốn'],
        1954 => ['Giáp Ngọ', 'Kim', 'Khảm', 'Cấn'],
        1955 => ['Ất Mùi', 'Kim', 'Ly', 'Càn'],
        1956 => ['Bính Thân', 'Hỏa', 'Cấn', 'Đoài'],
        1957 => ['Đinh Dậu', 'Hỏa', 'Đoài', 'Cấn'],
        1958 => ['Mậu Tuất', 'Mộc', 'Càn', 'Ly'],
        1959 => ['Kỷ Hợi', 'Mộc', 'Khôn', 'Khảm'],
        1960 => ['Canh Tý', 'Thổ', 'Tốn', 'Khôn'],
        1961 => ['Tân Sửu', 'Thổ', 'Chấn', 'Chấn'],
        1962 => ['Nhâm Dần', 'Kim', 'Khôn', 'Tốn'],
        1963 => ['Quý Mão', 'Kim', 'Khảm', 'Cấn'],
        1964 => ['Giáp Thìn', 'Hỏa', 'Ly', 'Càn'],
        1965 => ['Ất Tỵ', 'Hỏa', 'Cấn', 'Đoài'],
        1966 => ['Bính Ngọ', 'Thủy', 'Đoài', 'Cấn'],
        1967 => ['Đinh Mùi', 'Thủy', 'Càn', 'Ly'],
        1968 => ['Mậu Thân', 'Thổ', 'Khôn', 'Khảm'],
        1969 => ['Kỷ Dậu', 'Thổ', 'Tốn', 'Khôn'],
        1970 => ['Canh Tuất', 'Kim', 'Chấn', 'Chấn'],
        1971 => ['Tân Hợi', 'Kim', 'Khôn', 'Tốn'],
        1972 => ['Nhâm Tý', 'Mộc', 'Khảm', 'Cấn'],
        1973 => ['Quý Sửu', 'Mộc', 'Ly', 'Càn'],
        1974 => ['Giáp Dần', 'Thủy', 'Cấn', 'Đoài'],
        1975 => ['Ất Mão', 'Thủy', 'Đoài', 'Cấn'],
        1976 => ['Bính Thìn', 'Thổ', 'Càn', 'Ly'],
        1977 => ['Đinh Tỵ', 'Thổ', 'Khôn', 'Khảm'],
        1978 => ['Mậu Ngọ', 'Hỏa', 'Tốn', 'Khôn'],
        1979 => ['Kỷ Mùi', 'Hỏa', 'Chấn', 'Chấn'],
        1980 => ['Canh Thân', 'Mộc', 'Khôn', 'Tốn'],
        1981 => ['Tân Dậu', 'Mộc', 'Khảm', 'Cấn'],
        1982 => ['Nhâm Tuất', 'Thủy', 'Ly', 'Càn'],
        1983 => ['Quý Hợi', 'Thủy', 'Cấn', 'Đoài'],
        1984 => ['Giáp Tý', 'Kim', 'Đoài', 'Cấn'],
        1985 => ['Ất Sửu', 'Kim', 'Càn', 'Ly'],
        1986 => ['Bính Dần', 'Hỏa', 'Khôn', 'Khảm'],
        1987 => ['Đinh Mão', 'Hỏa', 'Tốn', 'Khôn'],
        1988 => ['Mậu Thìn', 'Mộc', 'Chấn', 'Chấn'],
        1989 => ['Kỷ Tỵ', 'Mộc', 'Khôn', 'Tốn'],
        1990 => ['Canh Ngọ', 'Thổ', 'Khảm', 'Cấn'],
        1991 => ['Tân Mùi', 'Thổ', 'Ly', 'Càn'],
        1992 => ['Nhâm Thân', 'Kim', 'Cấn', 'Đoài'],
        1993 => ['Quý Dậu', 'Kim', 'Đoài', 'Cấn'],
        1994 => ['Giáp Tuất', 'Hỏa', 'Càn', 'Ly'],
        1995 => ['Ất Hợi', 'Hỏa', 'Khôn', 'Khảm'],
        1996 => ['Bính Tý', 'Thủy', 'Tốn', 'Khôn'],
        1997 => ['Đinh Sửu', 'Thủy', 'Chấn', 'Chấn'],
        1998 => ['Mậu Dần', 'Thổ', 'Khôn', 'Tốn'],
        1999 => ['Kỷ Mão', 'Thổ', 'Khảm', 'Cấn'],
        2000 => ['Canh Thìn', 'Kim', 'Ly', 'Càn'],
        2001 => ['Tân Tỵ', 'Kim', 'Cấn', 'Đoài'],
        2002 => ['Nhâm Ngọ', 'Mộc', 'Đoài', 'Cấn'],
        2003 => ['Quý Mùi', 'Mộc', 'Càn', 'Ly'],
        2004 => ['Giáp Thân', 'Thủy', 'Khôn', 'Khảm'],
        2005 => ['Ất Dậu', 'Thủy', 'Tốn', 'Khôn'],
        2006 => ['Bính Tuất', 'Thổ', 'Chấn', 'Chấn'],
        2007 => ['Đinh Hợi', 'Thổ', 'Khôn', 'Tốn'],
        2008 => ['Mậu Tý', 'Hỏa', 'Khảm', 'Cấn'],
        2009 => ['Kỷ Sửu', 'Hỏa', 'Ly', 'Càn'],
        2010 => ['Canh Dần', 'Mộc', 'Cấn', 'Đoài'],
        2011 => ['Tân Mão', 'Mộc', 'Đoài', 'Cấn'],
        2012 => ['Nhâm Thìn', 'Thủy', 'Càn', 'Ly'],
        2013 => ['Quý Tỵ', 'Thủy', 'Khôn', 'Khảm'],
        2014 => ['Giáp Ngọ', 'Kim', 'Tốn', 'Khôn'],
        2015 => ['Ất Mùi', 'Kim', 'Chấn', 'Chấn'],
        2016 => ['Bính Thân', 'Hỏa', 'Khôn', 'Tốn'],
        2017 => ['Đinh Dậu', 'Hỏa', 'Khảm', 'Cấn'],
        2018 => ['Mậu Tuất', 'Mộc', 'Ly', 'Càn'],
        2019 => ['Kỷ Hợi', 'Mộc', 'Cấn', 'Đoài'],
        2020 => ['Canh Tý', 'Thổ', 'Đoài', 'Cấn'],
        2021 => ['Tân Sửu', 'Thổ', 'Càn', 'Ly'],
        2022 => ['Nhâm Dần', 'Kim', 'Khôn', 'Khảm'],
        2023 => ['Qúy Mão', 'Kim', 'Tốn', 'Khôn'],
        2024 => ['Giáp Thìn', 'Hỏa', 'Chấn', 'Chấn'],
        2025 => ['Ất Tỵ', 'Hỏa', 'Khôn', 'Tốn'],
        2026 => ['Bính Ngọ', 'Thủy', 'Khảm', 'Cấn'],
        2027 => ['Đinh Mùi', 'Thủy', 'Ly', 'Càn'],
        2028 => ['Mậu Thân', 'Thổ', 'Cấn', 'Đoài'],
        2029 => ['Kỷ Dậu', 'Thổ', 'Đoài', 'Cấn'],
        2030 => ['Canh Tuất', 'Kim', 'Càn', 'Ly'],
    ];
    public $nguHanh = [
        'Kim' => ['Thổ', 'Kim'],
        'Thủy' => ['Kim', 'Thủy'],
        'Mộc' => ['Thủy', 'Mộc'],
        'Hỏa' => ['Mộc', 'Hỏa'],
        'Thổ' => ['Hỏa', 'Thổ'],
    ];

    public $tuoiHop = [
        'Tý' => [
            'Nhị hợp' => 'Sửu',
            'Tam hợp' => 'Thân, Tý, Thìn',
            'Lục xung' => 'Ngọ',
            'Tương hại' => 'Mùi',
            'Hình' => 'Mão',
            'Sát' => 'Mùi',
        ],
        'Sửu' => [
            'Nhị hợp' => 'Tý',
            'Tam hợp' => 'Tỵ, Dậu, Sửu',
            'Lục xung' => 'Mùi',
            'Tương hại' => 'Ngọ',
            'Hình' => 'Tuất, Sửu, Mùi',
            'Sát' => 'Thìn',
        ],
        'Dần' => [
            'Nhị hợp' => 'Hợi',
            'Tam hợp' => 'Dần, Ngọ, Tuất',
            'Lục xung' => 'Thân',
            'Tương hại' => 'Tỵ',
            'Hình' => 'Thân, Dần, Tỵ',
            'Sát' => 'Sửu',
        ],
        'Mão' => [
            'Nhị hợp' => 'Tuất',
            'Tam hợp' => 'Hợi, Mão, Mùi',
            'Lục xung' => 'Dậu',
            'Tương hại' => 'Thìn',
            'Hình' => 'Tý',
            'Sát' => 'Tuất',
        ],
        'Thìn' => [
            'Nhị hợp' => 'Dậu',
            'Tam hợp' => 'Thân, Tý, Thìn',
            'Lục xung' => 'Tuất',
            'Tương hại' => 'Mão',
            'Hình' => 'Thìn',
            'Sát' => 'Mùi',
        ],
        'Tỵ' => [
            'Nhị hợp' => 'Thân',
            'Tam hợp' => 'Tỵ, Dậu, Sửu',
            'Lục xung' => 'Hợi',
            'Tương hại' => 'Dần',
            'Hình' => 'Dần, Tỵ, Thân',
            'Sát' => 'Thìn',
        ],
        'Ngọ' => [
            'Nhị hợp' => 'Mùi',
            'Tam hợp' => 'Dần, Ngọ, Tuất',
            'Lục xung' => 'Tý',
            'Tương hại' => 'Sửu',
            'Hình' => 'Ngọ',
            'Sát' => 'Sửu',
        ],
        'Mùi' => [
            'Nhị hợp' => 'Ngọ',
            'Tam hợp' => 'Hợi, Mão, Mùi',
            'Lục xung' => 'Sửu',
            'Tương hại' => 'Tý',
            'Hình' => 'Sửu, Mùi, Tuất',
            'Sát' => 'Tuất',
        ],
        'Thân' => [
            'Nhị hợp' => 'Tỵ',
            'Tam hợp' => 'Thân, Tý, Thìn',
            'Lục xung' => 'Dần',
            'Tương hại' => 'Hợi',
            'Hình' => 'Tỵ, Thân, Dần',
            'Sát' => 'Mùi',
        ],
        'Dậu' => [
            'Nhị hợp' => 'Thìn',
            'Tam hợp' => 'Tỵ, Dậu, Sửu',
            'Lục xung' => 'Mão',
            'Tương hại' => 'Tuất',
            'Hình' => 'Dậu',
            'Sát' => 'Thìn',
        ],
        'Tuất' => [
            'Nhị hợp' => 'Mão',
            'Tam hợp' => 'Dần, Ngọ, Tuất',
            'Lục xung' => 'Thìn',
            'Tương hại' => 'Dậu',
            'Hình' => 'Mùi, Tuất, Sửu',
            'Sát' => 'Sửu',
        ],
        'Hợi' => [
            'Nhị hợp' => 'Dần',
            'Tam hợp' => 'Hợi, Mão, Mùi',
            'Lục xung' => 'Tỵ',
            'Tương hại' => 'Thân',
            'Hình' => 'Hợi',
            'Sát' => 'Tuất',
        ],
    ];



    public $son = [
        'Nhâm' => [
            'Lộc' => 'Hợi',
            'Mã' => '',
            'Quý nhân' => 'Mão (+), Tỵ (-)',
            'Văn xương, Văn khúc' => 'Dần, Thân',
        ],
        'Tý' => [
            'Lộc' => 'Ngọ',
            'Mã' => 'Dần',
            'Quý nhân' => '',
            'Văn xương, Văn khúc' => '',
        ],
        'Quý' => [
            'Lộc' => 'Tý',
            'Mã' => '',
            'Quý nhân' => 'Tỵ (+), Mão (-)',
            'Văn xương, Văn khúc' => 'Dậu, Mão',
        ],
        'Sửu' => [
            'Lộc' => 'Ngọ',
            'Mã' => 'Hợi',
            'Quý nhân' => '',
            'Văn xương, Văn khúc' => '',
        ],
        'Cấn' => [
            'Lộc' => 'Tỵ',
            'Mã' => '',
            'Quý nhân' => 'Dậu (+)',
            'Văn xương, Văn khúc' => '',
        ],
        'Dần' => [
            'Lộc' => 'Hợi',
            'Mã' => 'Thân',
            'Quý nhân' => '',
            'Văn xương, Văn khúc' => '',
        ],
        'Giáp' => [
            'Lộc' => 'Dần',
            'Mã' => '',
            'Quý nhân' => 'Mùi (+), Sửu (-)',
            'Văn xương, Văn khúc' => 'Tỵ, Hợi',
        ],
        'Mão' => [
            'Lộc' => 'Thân',
            'Mã' => 'Tỵ',
            'Quý nhân' => '',
            'Văn xương, Văn khúc' => '',
        ],
        'Ất' => [
            'Lộc' => 'Mão',
            'Mã' => '',
            'Quý nhân' => 'Thân (+), Tý (-)',
            'Văn xương, Văn khúc' => 'Tý, Ngọ',
        ],
        'Thìn' => [
            'Lộc' => 'Tý',
            'Mã' => 'Dần',
            'Quý nhân' => '',
            'Văn xương, Văn khúc' => '',
        ],
        'Tốn' => [
            'Lộc' => 'Dậu',
            'Mã' => '',
            'Quý nhân' => 'Dần (+)',
            'Văn xương, Văn khúc' => '',
        ],
        'Tỵ' => [
            'Lộc' => 'Ngọ',
            'Mã' => 'Hợi',
            'Quý nhân' => '',
            'Văn xương, Văn khúc' => '',
        ],
        'Bính' => [
            'Lộc' => 'Tỵ',
            'Mã' => '',
            'Quý nhân' => 'Dậu (+), Hợi (-)',
            'Văn xương, Văn khúc' => 'Thân, Dần',
        ],
        'Ngọ' => [
            'Lộc' => 'Hợi',
            'Mã' => 'Thân',
            'Quý nhân' => '',
            'Văn xương, Văn khúc' => '',
        ],
        'Đinh' => [
            'Lộc' => 'Ngọ',
            'Mã' => '',
            'Quý nhân' => 'Hợi (+), Dậu (-)',
            'Văn xương, Văn khúc' => 'Mão, Dậu',
        ],
        'Mùi' => [
            'Lộc' => 'Thân',
            'Mã' => 'Tỵ',
            'Quý nhân' => '',
            'Văn xương, Văn khúc' => '',
        ],
        'Khôn' => [
            'Lộc' => 'Mão',
            'Mã' => '',
            'Quý nhân' => 'Thân (+)',
            'Văn xương, Văn khúc' => '',
        ],
        'Thân' => [
            'Lộc' => 'Tý',
            'Mã' => 'Dần',
            'Quý nhân' => '',
            'Văn xương, Văn khúc' => '',
        ],
        'Canh' => [
            'Lộc' => 'Thân',
            'Mã' => '',
            'Quý nhân' => 'Sửu (+), Mùi (-)',
            'Văn xương, Văn khúc' => 'Hợi, Tỵ',
        ],
        'Dậu' => [
            'Lộc' => 'Ngọ',
            'Mã' => 'Hợi',
            'Quý nhân' => '',
            'Văn xương, Văn khúc' => '',
        ],
        'Tân' => [
            'Lộc' => 'Dậu',
            'Mã' => '',
            'Quý nhân' => 'Dần (+), Ngọ (-)',
            'Văn xương, Văn khúc' => 'Ngọ, Tý',
        ],
        'Tuất' => [
            'Lộc' => 'Hợi',
            'Mã' => 'Thân',
            'Quý nhân' => '',
            'Văn xương, Văn khúc' => '',
        ],
        'Càn' => [
            'Lộc' => 'Dần',
            'Mã' => '',
            'Quý nhân' => 'Mùi (+)',
            'Văn xương, Văn khúc' => '',
        ],
        'Hợi' => [
            'Lộc' => 'Thân',
            'Mã' => 'Tỵ',
            'Quý nhân' => '',
            'Văn xương, Văn khúc' => '',
        ],
        'Mậu' => [
            'Lộc' => 'Tỵ',
            'Mã' => '',
            'Quý nhân' => 'Mùi (+), Sửu (-)',
            'Văn xương, Văn khúc' => 'Thân, Dần',
        ],
        'Kỷ' => [
            'Lộc' => 'Ngọ',
            'Mã' => '',
            'Quý nhân' => 'Tý (+), Thân (-)',
            'Văn xương, Văn khúc' => 'Mão, Dậu',
        ],
    ];

    public $can = [
        'Giáp' => [
            'Hóa' => 'Kỷ',
            'Xung' => 'Canh',
            'Phá' => 'Mậu',
            'Đô thiên' => 'Thìn - Tỵ',
        ],
        'Ất' => [
            'Hóa' => 'Canh',
            'Xung' => 'Tân',
            'Phá' => 'Kỷ',
            'Đô thiên' => 'Dần - Mão',
        ],
        'Bính' => [
            'Hóa' => 'Tân',
            'Xung' => 'Nhâm',
            'Phá' => 'Canh',
            'Đô thiên' => 'Tuất - Hợi',
        ],
        'Đinh' => [
            'Hóa' => 'Nhâm',
            'Xung' => 'Quý',
            'Phá' => 'Tân',
            'Đô thiên' => 'Thân - Dậu',
        ],
        'Mậu' => [
            'Hóa' => 'Quý',
            'Xung' => '-',
            'Phá' => 'Giáp, Nhâm',
            'Đô thiên' => 'Ngọ - Mùi',
        ],
        'Kỷ' => [
            'Hóa' => 'Giáp',
            'Xung' => '-',
            'Phá' => 'Ất, Quý',
            'Đô thiên' => 'Thìn - Tỵ',
        ],
        'Canh' => [
            'Hóa' => 'Ất',
            'Xung' => 'Giáp',
            'Phá' => 'Bính',
            'Đô thiên' => 'Dần - Mão',
        ],
        'Tân' => [
            'Hóa' => 'Bính',
            'Xung' => 'Ất',
            'Phá' => 'Đinh',
            'Đô thiên' => 'Tuất - Hợi',
        ],
        'Nhâm' => [
            'Hóa' => 'Đinh',
            'Xung' => 'Bính',
            'Phá' => 'Mậu',
            'Đô thiên' => 'Thân - Dậu',
        ],
        'Quý' => [
            'Hóa' => 'Mậu',
            'Xung' => 'Đinh',
            'Phá' => 'Kỷ',
            'Đô thiên' => 'Ngọ - Mùi',
        ],
    ];

    public $tutruong = [
        'Sinh Khí' => [
            14 => 4,
            41 => 4,
            67 => 3,
            76 => 3,
            39 => 2,
            93 => 2,
            28 => 1,
            82 => 1,
        ],
        'Thiên Y' => [
            13 => 4,
            31 => 4,
            68 => 3,
            86 => 3,
            49 => 2,
            94 => 2,
            27 => 1,
            72 => 1,
        ],
        'Diên Niên' => [
            19 => 4,
            91 => 4,
            78 => 3,
            87 => 3,
            34 => 2,
            43 => 2,
            26 => 1,
            62 => 1,
        ],
        'Phục Vị' => [
            11 => 4,
            22 => 4,
            88 => 3,
            99 => 3,
            66 => 2,
            77 => 2,
            33 => 1,
            44 => 1,
        ],
        'Lục Sát' => [
            16 => 4,
            61 => 4,
            47 => 3,
            74 => 3,
            38 => 2,
            83 => 2,
            29 => 1,
            92 => 1,
        ],
        'Họa Hại' => [
            17 => 4,
            71 => 4,
            89 => 3,
            98 => 3,
            46 => 2,
            64 => 2,
            23 => 1,
            32 => 1,
        ],
        'Tuyệt Mệnh' => [
            12 => 4,
            21 => 4,
            69 => 3,
            96 => 3,
            48 => 2,
            84 => 2,
            37 => 1,
            73 => 1,
        ],
        'Ngũ Quỷ' => [
            18 => 4,
            81 => 4,
            79 => 3,
            97 => 3,
            36 => 2,
            63 => 2,
            24 => 1,
            42 => 1,
        ],
    ];

    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

}
